version: "3.4"
networks:
  #可以自定义network名称，这里使用default表示如果不在service中单独配置就使用该设置 
  default: 
    external: 
      name: app-net
services:
  gateway1:
    image: xlvchao/spartacus-gateway:1.0.0
    container_name: gateway1
    restart: always
    environment:
      - JAVA_OPTS=-server -Xms128M -Xmx256M -Xmn64M -XX:MetaspaceSize=64M -XX:MaxMetaspaceSize=128M
      - instanceIp=10.0.0.10
      - instancePort=2001
      - APOLLO_META="http://10.0.0.11:8080,http://10.0.0.9:8081,http://10.0.0.16:8082"
      - APOLLO_ACCESSKEY_SECRET=ae0a90ac27e7470c8b3ccd40e7ddfcb8
      - CSP_SENTINEL_DASHBOARD_SERVER=10.0.0.10:8848
      - PROJECT_NAME=spartacus-gateway
      - CSP_SENTINEL_API_PORT=8719
    volumes:
      - /opt/settings:/opt/settings
    ports:
      - 2001:2001
      - 8719:8719
  gateway2:
    image: xlvchao/spartacus-gateway:1.0.0
    container_name: gateway2
    restart: always
    environment:
      - JAVA_OPTS=-server -Xms128M -Xmx256M -Xmn64M -XX:MetaspaceSize=64M -XX:MaxMetaspaceSize=128M
      - instanceIp=10.0.0.4
      - instancePort=2002
      - APOLLO_META="http://10.0.0.11:8080,http://10.0.0.9:8081,http://10.0.0.16:8082"
      - APOLLO_ACCESSKEY_SECRET=ae0a90ac27e7470c8b3ccd40e7ddfcb8
      - CSP_SENTINEL_DASHBOARD_SERVER=10.0.0.10:8848
      - PROJECT_NAME=spartacus-gateway
      - CSP_SENTINEL_API_PORT=8720
    volumes:
      - /opt/settings:/opt/settings
    ports:
      - 2002:2002
      - 8720:8720
  gateway3:
    image: xlvchao/spartacus-gateway:1.0.0
    container_name: gateway3
    restart: always
    environment:
      - JAVA_OPTS=-server -Xms128M -Xmx256M -Xmn64M -XX:MetaspaceSize=64M -XX:MaxMetaspaceSize=128M
      - instanceIp=10.0.0.14
      - instancePort=2003
      - APOLLO_META="http://10.0.0.11:8080,http://10.0.0.9:8081,http://10.0.0.16:8082"
      - APOLLO_ACCESSKEY_SECRET=ae0a90ac27e7470c8b3ccd40e7ddfcb8
      - CSP_SENTINEL_DASHBOARD_SERVER=10.0.0.10:8848
      - PROJECT_NAME=spartacus-gateway
      - CSP_SENTINEL_API_PORT=8721
    volumes:
      - /opt/settings:/opt/settings
    ports:
      - 2003:2003
      - 8721:8721