version: "3.4"
networks:
  #可以自定义network名称，这里使用default表示如果不在service中单独配置就使用该设置 
  default: 
    external: 
      name: app-net
services:
  discovery1:
    image: xlvchao/spartacus-discovery:1.0.0
    container_name: discovery1
    restart: always
    environment:
      - JAVA_OPTS=-server -Xms128M -Xmx256M -Xmn64M -XX:MetaspaceSize=64M -XX:MaxMetaspaceSize=128M
      - instanceIp=10.0.0.10
      - instancePort=1001
      - APOLLO_META="http://10.0.0.11:8080,http://10.0.0.9:8081,http://10.0.0.16:8082"
      - APOLLO_ACCESSKEY_SECRET=ae6dc6ef5f2146efae043ca8db1f18c6
    volumes:
      - /opt/settings:/opt/settings
    ports:
      - 1001:1001
  discovery2:
    image: xlvchao/spartacus-discovery:1.0.0
    container_name: discovery2
    restart: always
    environment:
      - JAVA_OPTS=-server -Xms128M -Xmx256M -Xmn64M -XX:MetaspaceSize=64M -XX:MaxMetaspaceSize=128M
      - instanceIp=10.0.0.4
      - instancePort=1002
      - APOLLO_META="http://10.0.0.11:8080,http://10.0.0.9:8081,http://10.0.0.16:8082"
      - APOLLO_ACCESSKEY_SECRET=ae6dc6ef5f2146efae043ca8db1f18c6
    volumes:
      - /opt/settings:/opt/settings
    ports:
      - 1002:1002
  discovery3:
    image: xlvchao/spartacus-discovery:1.0.0
    container_name: discovery3
    restart: always
    environment:
      - JAVA_OPTS=-server -Xms128M -Xmx256M -Xmn64M -XX:MetaspaceSize=64M -XX:MaxMetaspaceSize=128M
      - instanceIp=10.0.0.14
      - instancePort=1003
      - APOLLO_META="http://10.0.0.11:8080,http://10.0.0.9:8081,http://10.0.0.16:8082"
      - APOLLO_ACCESSKEY_SECRET=ae6dc6ef5f2146efae043ca8db1f18c6
    volumes:
      - /opt/settings:/opt/settings
    ports:
      - 1003:1003