version: "3.4"
networks:
  #可以自定义network名称，这里使用default表示如果不在service中单独配置就使用该设置 
  default: 
    external: 
      name: app-net
services:
  article1:
    image: xlvchao/spartacus-article:1.0.0
    container_name: article1
    restart: always
    environment:
      - JAVA_OPTS=-server -Xms128M -Xmx256M -Xmn64M -XX:MetaspaceSize=64M -XX:MaxMetaspaceSize=128M
      - instanceIp=10.0.0.10
      - instancePort=5001
      - xxlJobExecutorPort=5011
      - APOLLO_META="http://10.0.0.11:8080,http://10.0.0.9:8081,http://10.0.0.16:8082"
      - APOLLO_ACCESSKEY_SECRET=ed42b638bb7440e5ad8058b55cf66ef0
    volumes:
      - /opt/settings:/opt/settings
    ports:
      - 5001:5001
      - 5011:5011
#  article2:
#    image: xlvchao/spartacus-article:1.0.0
#    container_name: article2
#    restart: always
#    environment:
#      - JAVA_OPTS=-server -Xms128M -Xmx256M -Xmn64M -XX:MetaspaceSize=64M -XX:MaxMetaspaceSize=128M
#      - instanceIp=10.0.0.4
#      - instancePort=5002
#      - xxlJobExecutorPort=5012
#      - APOLLO_META="http://10.0.0.11:8080,http://10.0.0.9:8081,http://10.0.0.16:8082"
#      - APOLLO_ACCESSKEY_SECRET=ed42b638bb7440e5ad8058b55cf66ef0
#    volumes:
#      - /opt/settings:/opt/settings
#    ports:
#      - 5002:5002
#      - 5012:5012
#  article3:
#    image: xlvchao/spartacus-article:1.0.0
#    container_name: article3
#    restart: always
#    environment:
#      - JAVA_OPTS=-server -Xms128M -Xmx256M -Xmn64M -XX:MetaspaceSize=64M -XX:MaxMetaspaceSize=128M
#      - instanceIp=10.0.0.14
#      - instancePort=5003
#      - xxlJobExecutorPort=5013
#      - APOLLO_META="http://10.0.0.11:8080,http://10.0.0.9:8081,http://10.0.0.16:8082"
#      - APOLLO_ACCESSKEY_SECRET=ed42b638bb7440e5ad8058b55cf66ef0
#    volumes:
#      - /opt/settings:/opt/settings
#    ports:
#      - 5003:5003
#      - 5013:5013